# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

default:
  image: node:14

stages: # List of stages for jobs, and their order of execution
  - test
  - cache
  - preview

.yarn_cache_template: &yarn_cache_template
  key:
    files:
      - package.json
      - yarn.lock
  paths:
    - .cache_exists
    - .yarn-cache/
    - node_modules/
    - '**/node_modules/'
  policy: pull

# These jobs are run in parallel within the test stage:
combined-job:
  stage: test
  cache:
    <<: *yarn_cache_template
  before_script:
    - yarn install --cache-folder .yarn-cache
  script:
    - yarn lint
    - HARDHAT_NO_MNEMONIC=yes yarn run build:contracts && yarn test
    - yarn workspace @zkp-staking/contracts build:types
    - yarn run build:dapp
    - yarn run test:dapp

build-cache:
  stage: cache
  cache:
    <<: *yarn_cache_template
    policy: pull-push
  script:
    - |
      [[ -f .cache_exists ]] && echo "cache already exists" && exit 111
    - echo > .cache_exists
  allow_failure:
    exit_codes: 111 # disable push cache

preview:
  stage: preview
  only:
    - merge_requests
  script:
    - |
      apt-get update
      apt-get -y install jq
      if [ -n "$CI_MERGE_REQUEST_IID" ]; then
        thread_id=$(
          curl \
              --data-urlencode "body=## After build, preview will 🚀[be here!](https://pr-${CI_MERGE_REQUEST_IID}.${AMPLIFY_APP_ID}.amplifyapp.com/)" \
              --request POST \
              --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" \
              "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/discussions" \
          | jq -r .id
        )
        curl -v -X PUT \
          --header "PRIVATE-TOKEN: $GITLAB_ACCESS_TOKEN" \
          "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/discussions/$thread_id?resolved=true" \
        | jq .
      fi
