import * as path from 'path';

import circom_wasm_tester from 'circom_tester';
const wasm_tester = circom_wasm_tester.wasm;

import {getOptions} from './helpers/circomTester';
import {wtns} from 'snarkjs';

describe('Main z-transaction - ZeroInput - Witness computation', async function (this: any) {
    let circuit: any;
    let mainTxWasm: any;
    let mainTxWitness: any;

    this.timeout(10000000);

    before(async () => {
        const opts = getOptions();
        const input = path.join(
            opts.basedir,
            './circuits/mainZTransactionV1.circom',
        );
        circuit = await wasm_tester(input, opts);

        mainTxWasm = path.join(
            opts.basedir,
            './compiled/zTransaction/circuits.wasm',
        );

        mainTxWitness = path.join(
            opts.basedir,
            './compiled/generate_witness.js',
        );
    });

    const zeroInput = {
        extraInputsHash: BigInt(0n),

        depositAmount: BigInt(0n),
        depositChange: BigInt(0n),
        withdrawAmount: BigInt(0n),
        withdrawChange: BigInt(0n),
        donatedAmountZkp: BigInt(0n),
        token: BigInt(0n),
        tokenId: BigInt(0n),
        utxoZAsset: BigInt(0n),

        // zAsset
        zAssetId: BigInt(0n),
        zAssetToken: BigInt(0n),
        zAssetTokenId: BigInt(0n),
        zAssetNetwork: BigInt(0n),
        zAssetOffset: BigInt(0n),
        zAssetWeight: BigInt(0n),
        zAssetScale: BigInt(1n),
        zAssetMerkleRoot: BigInt(0n),
        zAssetPathIndices: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],
        zAssetPathElements: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],

        zAssetIdZkp: BigInt(0n),
        zAssetTokenZkp: BigInt(0n),
        zAssetTokenIdZkp: BigInt(0n),
        zAssetNetworkZkp: BigInt(0n),
        zAssetOffsetZkp: BigInt(0n),
        zAssetWeightZkp: BigInt(0n),
        zAssetScaleZkp: BigInt(1n),
        zAssetPathIndicesZkp: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],
        zAssetPathElementsZkp: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],

        forTxReward: BigInt(0n),
        forUtxoReward: BigInt(0n),
        forDepositReward: BigInt(0n),

        spendTime: BigInt(0n),

        // input 'zAsset UTXOs'
        // to switch-off:
        //      1) utxoInAmount = 0
        //      2) utxoInSpendPrivKey = 0
        //      3) utxoInSpendKeyRandom = 0
        // switch-off control is used for:
        //      1) deposit only tx
        //      2) deposit & zAccount::zkpAmount
        //      3) deposit & zAccount::zkpAmount & withdraw
        //      4) deposit & withrdaw

        utxoInSpendPrivKey: [BigInt(0n), BigInt(0n)],
        utxoInSpendKeyRandom: [BigInt(0n), BigInt(0n)],
        utxoInAmount: [BigInt(0n), BigInt(0n)],
        utxoInOriginZoneId: [BigInt(0n), BigInt(0n)],
        utxoInOriginZoneIdOffset: [BigInt(0n), BigInt(0n)],
        utxoInOriginNetworkId: [BigInt(0n), BigInt(0n)],
        utxoInTargetNetworkId: [BigInt(0n), BigInt(0n)],
        utxoInCreateTime: [BigInt(0n), BigInt(0n)],
        utxoInZAccountId: [BigInt(0n), BigInt(0n)],
        utxoInMerkleTreeSelector: [
            [BigInt(0n), BigInt(0n)],
            [BigInt(0n), BigInt(0n)],
        ],
        utxoInPathIndices: [
            [
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
            ],
            [
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
            ],
        ],
        utxoInPathElements: [
            [
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
            ],
            [
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
                BigInt(0n),
            ],
        ],
        utxoInNullifier: [BigInt(0n), BigInt(0n)],

        // input 'zAccount UTXO'
        zAccountUtxoInId: BigInt(0n),
        zAccountUtxoInZkpAmount: BigInt(0n),
        zAccountUtxoInPrpAmount: BigInt(0n),
        zAccountUtxoInZoneId: BigInt(0n),
        zAccountUtxoInNetworkId: BigInt(0n),
        zAccountUtxoInExpiryTime: BigInt(0n),
        zAccountUtxoInNonce: BigInt(0n),
        zAccountUtxoInTotalAmountPerTimePeriod: BigInt(0n),
        zAccountUtxoInCreateTime: BigInt(0n),
        zAccountUtxoInRootSpendPubKey: [BigInt(0n), BigInt(1n)],
        zAccountUtxoInReadPubKey:[BigInt(0n), BigInt(1n)],
        zAccountUtxoInNullifierPubKey:[BigInt(0n), BigInt(1n)],
        zAccountUtxoInMasterEOA: BigInt(0n),
        zAccountUtxoInSpendPrivKey: BigInt(0n),
        zAccountUtxoInReadPrivKey:BigInt(0n),
        zAccountUtxoInNullifierPrivKey:BigInt(0n),
        zAccountUtxoInMerkleTreeSelector: [BigInt(0n), BigInt(0n)],
        zAccountUtxoInPathIndices: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],
        zAccountUtxoInPathElements: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],
        zAccountUtxoInNullifier: BigInt(0n),

        zAccountBlackListLeaf: BigInt(0n),
        zAccountBlackListMerkleRoot: BigInt(0n),
        zAccountBlackListPathElements: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],

        // zZone
        zZoneOriginZoneIDs: BigInt(0n),
        zZoneTargetZoneIDs: BigInt(0n),
        zZoneNetworkIDsBitMap: BigInt(0n),
        zZoneTrustProvidersMerkleTreeLeafIDsAndRulesList: BigInt(0n),
        zZoneKycExpiryTime: BigInt(0n),
        zZoneKytExpiryTime: BigInt(0n),
        zZoneDepositMaxAmount: BigInt(0n),
        zZoneWithrawMaxAmount: BigInt(0n),
        zZoneInternalMaxAmount: BigInt(0n),
        zZoneMerkleRoot: BigInt(0n),
        zZonePathElements: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],
        zZonePathIndices: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],
        zZoneEdDsaPubKey: [BigInt(0n), BigInt(0n)],
        zZoneDataEscrowEphimeralRandom: BigInt(0n),
        zZoneDataEscrowEphimeralPubKeyAx: BigInt(0n),
        zZoneDataEscrowEphimeralPubKeyAy: BigInt(1n),
        zZoneZAccountIDsBlackList: BigInt(
            '1766847064778384329583297500742918515827483896875618958121606201292619775',
        ),
        zZoneMaximumAmountPerTimePeriod: BigInt(0n),
        zZoneTimePeriodPerMaximumAmount: BigInt(0n),

        zZoneDataEscrowEncryptedMessageAx: [BigInt(0n)],
        zZoneDataEscrowEncryptedMessageAy: [BigInt(1n)],

        kytEdDsaPubKey: [BigInt(0n), BigInt(0n)],
        kytEdDsaPubKeyExpiryTime: BigInt(0n),
        trustProvidersMerkleRoot: BigInt(0n),
        kytPathElements: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],
        kytPathIndices: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],
        kytMerkleTreeLeafIDsAndRulesOffset: BigInt(0n),

        kytDepositSignedMessagePackageType: BigInt(2n),
        kytDepositSignedMessageTimestamp: BigInt(0n),
        kytDepositSignedMessageSender: BigInt(0n),
        kytDepositSignedMessageReceiver: BigInt(0n),
        kytDepositSignedMessageToken: BigInt(0n),
        kytDepositSignedMessageSessionId: BigInt(0n),
        kytDepositSignedMessageRuleId: BigInt(0n),
        kytDepositSignedMessageAmount: BigInt(0n),
        kytDepositSignedMessageSigner:BigInt(0n),
        kytDepositSignedMessageHash: BigInt(0n),
        kytDepositSignature: [BigInt(0n), BigInt(0n), BigInt(0n)],

        kytWithdrawSignedMessagePackageType: BigInt(2n),
        kytWithdrawSignedMessageTimestamp: BigInt(0n),
        kytWithdrawSignedMessageSender: BigInt(0n),
        kytWithdrawSignedMessageReceiver: BigInt(0n),
        kytWithdrawSignedMessageToken: BigInt(0n),
        kytWithdrawSignedMessageSessionId: BigInt(0n),
        kytWithdrawSignedMessageRuleId: BigInt(0n),
        kytWithdrawSignedMessageAmount: BigInt(0n),
        kytWithdrawSignedMessageSigner:BigInt(0n),
        kytWithdrawSignedMessageHash: BigInt(0n),
        kytWithdrawSignature: [BigInt(0n), BigInt(0n), BigInt(0n)],

        dataEscrowPubKey: [BigInt(0n), BigInt(0n)],
        dataEscrowPubKeyExpiryTime: BigInt(0n),
        dataEscrowEphimeralRandom: BigInt(0n),
        dataEscrowEphimeralPubKeyAx: BigInt(0n),
        dataEscrowEphimeralPubKeyAy: BigInt(1n),
        dataEscrowPathElements: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],
        dataEscrowPathIndices: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],

        dataEscrowEncryptedMessageAx: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],
        dataEscrowEncryptedMessageAy: [
            BigInt(1n),
            BigInt(1n),
            BigInt(1n),
            BigInt(1n),
            BigInt(1n),
            BigInt(1n),
            BigInt(1n),
            BigInt(1n),
            BigInt(0n),
            BigInt(0n),
        ],
        daoDataEscrowPubKey: [BigInt(0n), BigInt(0n)],
        daoDataEscrowEphimeralRandom: BigInt(0n),
        daoDataEscrowEphimeralPubKeyAx: BigInt(0n),
        daoDataEscrowEphimeralPubKeyAy: BigInt(1n),

        daoDataEscrowEncryptedMessageAx: [BigInt(0n), BigInt(0n), BigInt(0n)],
        daoDataEscrowEncryptedMessageAy: [BigInt(1n), BigInt(1n), BigInt(1n)],

        utxoOutCreateTime: BigInt(0n),
        utxoOutAmount: [BigInt(0n), BigInt(0n)],
        utxoOutOriginNetworkId: [BigInt(0n), BigInt(0n)],
        utxoOutTargetNetworkId: [BigInt(0n), BigInt(0n)],
        utxoOutTargetZoneId: [BigInt(0n), BigInt(0n)],
        utxoOutTargetZoneIdOffset: [BigInt(0n), BigInt(0n)],
        utxoOutSpendPubKeyRandom: [BigInt(0n), BigInt(0n)],
        utxoOutRootSpendPubKey: [
            [BigInt(0n), BigInt(0n)],
            [BigInt(0n), BigInt(0n)],
        ],
        utxoOutCommitment: [BigInt(0n), BigInt(0n)],

        zAccountUtxoOutZkpAmount: BigInt(0n),
        zAccountUtxoOutSpendKeyRandom: BigInt(0n),
        zAccountUtxoOutCommitment: BigInt(0n),

        chargedAmountZkp: BigInt(0n),

        zNetworkId: BigInt(0n),
        zNetworkChainId: BigInt(0n),
        zNetworkIDsBitMap: BigInt(0n),
        zNetworkTreeMerkleRoot: BigInt(0n),
        zNetworkTreePathElements: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],
        zNetworkTreePathIndices: [
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
            BigInt(0n),
        ],

        staticTreeMerkleRoot: BigInt(0n),

        forestMerkleRoot: BigInt(0n),
        taxiMerkleRoot: BigInt(0n),
        busMerkleRoot: BigInt(0n),
        ferryMerkleRoot: BigInt(0n),

        // salt
        salt: BigInt(0n),
        saltHash: BigInt(0n),

        // magical constraint - groth16 attack: https://geometry.xyz/notebook/groth16-malleability
        magicalConstraint: BigInt(0n),
    };

    it('should compute valid witness for zero input deposit only z-tx', async () => {
        await wtns.calculate(zeroInput, mainTxWasm, mainTxWitness, null);
        console.log('Witness calculation successful!');
    });
});
