// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: Copyright 2021-25 Panther Protocol Foundation
pragma solidity ^0.8.19;

// Indexes of public input for the main zk-circuit follows

uint256 constant MAIN_EXTRA_INPUT_HASH_IND = 0;
uint256 constant MAIN_DEPOSIT_AMOUNT_IND = 1;
uint256 constant MAIN_WITHDRAW_AMOUNT_IND = 2;
uint256 constant MAIN_ADDED_AMOUNT_ZKP_IND = 3;
uint256 constant MAIN_TOKEN_TYPE_AND_ADDRESS_IND = 4;
uint256 constant MAIN_TOKEN_ID_IND = 5;
uint256 constant MAIN_SPEND_TIME_IND = 6;
uint256 constant MAIN_ZASSET_UTXO_IN_NULLIFIER_1_IND = 7;
uint256 constant MAIN_ZASSET_UTXO_IN_NULLIFIER_2_IND = 8;
uint256 constant MAIN_ZACCOUNT_UTXO_IN_NULLIFIER_IND = 9;
uint256 constant MAIN_ZZONE_DATA_ESCROW_EPHIMERAL_PUB_KEY_AX_IND = 10;
uint256 constant MAIN_ZZONE_DATA_ESCROW_ENCRYPTED_MESSAGE_IND = 11;
uint256 constant MAIN_ZZONE_DATA_ESCROW_ENCRYPTED_MESSAGE_HMAC_IND = 12;
uint256 constant MAIN_KYT_DEPOSIT_SIGNED_MESSAGE_SENDER_IND = 13;
uint256 constant MAIN_KYT_DEPOSIT_SIGNED_MESSAGE_RECEIVER_IND = 14;
uint256 constant MAIN_KYT_DEPOSIT_SIGNED_MESSAGE_HASH_IND = 15;
uint256 constant MAIN_KYT_WITHDRAW_SIGNED_MESSAGE_SENDER_IND = 16;
uint256 constant MAIN_KYT_WITHDRAW_SIGNED_MESSAGE_RECEIVER_IND = 17;
uint256 constant MAIN_KYT_WITHDRAW_SIGNED_MESSAGE_HASH_IND = 18;
uint256 constant MAIN_KYT_INTERNAL_SIGNED_MESSAGE_HASH_IND = 19; //TODO: should be checked?
// indexes 20 to 24 are MAIN_DATA_ESCROW_ENCRYPTED_MESSAGE_IND
uint256 constant MAIN_DATA_ESCROW_ENCRYPTED_MESSAGE_HMAC_IND = 25;
uint256 constant MAIN_DAO_DATA_ESCROW_EPHIMERAL_PUB_KEY_AX_IND = 26;
uint256 constant MAIN_DAO_DATA_ESCROW_ENCRYPTED_MESSAGE_IND = 27;
uint256 constant MAIN_DAO_DATA_ESCROW_ENCRYPTED_MESSAGE_HMAC_IND = 28;
uint256 constant MAIN_UTXO_OUT_CREATE_TIME_IND = 29;
uint256 constant MAIN_ZASSET_UTXO_OUT_COMMITMENT_1_IND = 30;
uint256 constant MAIN_ZASSET_UTXO_OUT_COMMITMENT_2_IND = 31;
uint256 constant MAIN_ZACCOUNT_UTXO_OUT_COMMITMENT_IND = 32;
uint256 constant MAIN_CHARGED_AMOUNT_ZKP_IND = 33;
uint256 constant MAIN_ZNETWORK_CHAIN_ID_IND = 34;
uint256 constant MAIN_STATIC_MERKLE_ROOT_IND = 35;
uint256 constant MAIN_FOREST_MERKLE_ROOT_IND = 36;
uint256 constant MAIN_SALT_HASH_IND = 37;
uint256 constant MAIN_MAGICAL_CONSTRAINT_IND = 38;
