// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: Copyright 2021-25 Panther Protocol Foundation
pragma solidity ^0.8.19;

// Indexes of public input for the prpAccounting zk-circuit follows

uint256 constant PRP_ACCOUNTING_EXTRA_INPUT_HASH_IND = 0;
uint256 constant PRP_ACCOUNTING_ADDED_AMOUNT_ZKP_IND = 1;
uint256 constant PRP_ACCOUNTING_CHARGED_AMOUNT_ZKP_IND = 2;
uint256 constant PRP_ACCOUNTING_UTXO_OUT_CREATE_TIME_IND = 3;
uint256 constant PRP_ACCOUNTING_DEPOSIT_PRP_AMOUNT_IND = 4;
uint256 constant PRP_ACCOUNTING_WITHDRAW_PRP_AMOUNT_IND = 5;
uint256 constant PRP_ACCOUNTING_UTXO_COMMITMENT_PRIVATE_PART_IND = 6;
uint256 constant PRP_ACCOUNTING_ZASSET_SCALE_IND = 7;
uint256 constant PRP_ACCOUNTING_ZACCOUNT_UTXO_IN_NULLIFIER_IND = 8;
uint256 constant PRP_ACCOUNTING_ZACCOUNT_UTXO_OUT_COMMITMENT_IND = 9;
uint256 constant PRP_ACCOUNTING_ZNETWORK_CHAIN_ID_IND = 10;
uint256 constant PRP_ACCOUNTING_STATIC_MERKLE_ROOT_IND = 11;
uint256 constant PRP_ACCOUNTING_FOREST_MERKLE_ROOT_IND = 12;
uint256 constant PRP_ACCOUNTING_SALT_HASH_IND = 13;
uint256 constant PRP_ACCOUNTING_MAGICAL_CONSTRAINT_IND = 14;
