// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: Copyright 2024 Panther Ventures Limited Gibraltar
pragma solidity ^0.8.19;

uint256 constant ZSWAP_EXTRA_INPUTS_HASH_IND = 0;
uint256 constant ZSWAP_DEPOSIT_AMOUNT_IND = 1;
uint256 constant ZSWAP_WITHDRAW_AMOUNT_IND = 2;
uint256 constant ZSWAP_ADDED_AMOUNT_ZKP_IND = 3;
uint256 constant ZSWAP_EXISTING_TOKEN_TYPE_AND_ADDRESS_IND = 4;
uint256 constant ZSWAP_INCOMING_TOKEN_TYPE_AND_ADDRESS_IND = 5;
uint256 constant ZSWAP_EXISTING_TOKEN_ID_IND = 6;
uint256 constant ZSWAP_INCOMING_TOKEN_ID_IND = 7;
uint256 constant ZSWAP_EXISTING_ZASSET_SCALE_IND = 8;
uint256 constant ZSWAP_INCOMING_ZASSET_SCALE_IND = 9;
uint256 constant ZSWAP_ZZKP_SCALE_IND = 10;
uint256 constant ZSWAP_SPEND_TIME_IND = 11;
uint256 constant ZSWAP_ZASSET_UTXO_IN_NULLIFIER_1_IND = 12;
uint256 constant ZSWAP_ZASSET_UTXO_IN_NULLIFIER_2_IND = 13;
uint256 constant ZSWAP_ZACCOUNT_UTXO_IN_NULLIFIER_IND = 14;
uint256 constant ZSWAP_ZZONE_DATA_ESCROW_EPHIMERAL_PUB_KEY_AX_IND = 15;
uint256 constant ZSWAP_ZZONE_DATA_ESCROW_ENCRYPTED_MESSAGE_IND = 16;
uint256 constant ZSWAP_ZZONE_DATA_ESCROW_ENCRYPTED_MESSAGE_HMAC_IND = 17;
uint256 constant ZSWAP_KYT_DEPOSIT_SIGNED_MESSAGE_SENDER_IND = 18;
uint256 constant ZSWAP_KYT_DEPOSIT_SIGNED_MESSAGE_RECEIVER_IND = 19;
uint256 constant ZSWAP_KYT_DEPOSIT_SIGNED_MESSAGE_HASH_IND = 20;
uint256 constant ZSWAP_KYT_WITHDRAW_SIGNED_MESSAGE_SENDER_IND = 21;
uint256 constant ZSWAP_KYT_WITHDRAW_SIGNED_MESSAGE_RECEIVER_IND = 22;
uint256 constant ZSWAP_KYT_WITHDRAW_SIGNED_MESSAGE_HASH_IND = 23;
uint256 constant ZSWAP_KYT_INTERNAL_SIGNED_MESSAGE_HASH_IND = 24;
// indexes 25 to 29 are ZSWAP_DATA_ESCROW_ENCRYPTED_MESSAGE_IND
uint256 constant ZSWAP_DATA_ESCROW_ENCRYPTED_MESSAGE_HMAC_IND = 30;
uint256 constant ZSWAP_DAO_DATA_ESCROW_EPHIMERAL_PUB_KEY_AX_IND = 31;
// indexe 32 is ZSWAP_DAO_DATA_ESCROW_ENCRYPTED_MESSAGE_IND
uint256 constant ZSWAP_DAO_DATA_ESCROW_ENCRYPTED_MESSAGE_HMAC_IND = 33;
uint256 constant ZSWAP_UTXO_OUT_CREATE_TIME_IND = 34;
uint256 constant ZSWAP_ZASSET_UTXO_OUT_COMMITMENT_1_IND = 35;
uint256 constant ZSWAP_ZASSET_UTXO_OUT_COMMITMENT_2_PRIVATE_PART_IND = 36;
uint256 constant ZSWAP_ZACCOUNT_UTXO_OUT_COMMITMENT_IND = 37;
uint256 constant ZSWAP_CHARGED_AMOUNT_ZKP_IND = 38;
uint256 constant ZSWAP_ZNETWORK_CHAIN_ID_IND = 39;
uint256 constant ZSWAP_STATIC_MERKLE_ROOT_IND = 40;
uint256 constant ZSWAP_FOREST_MERKLE_ROOT_IND = 41;
uint256 constant ZSWAP_SALT_HASH_IND = 42;
uint256 constant ZSWAP_MAGICAL_CONSTRAINT_IND = 43;
