// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: Copyright 2024 Panther Ventures Limited Gibraltar
pragma solidity ^0.8.19;

uint256 constant MAIN_EXTRA_INPUT_HASH_IND = 0;
uint256 constant MAIN_DEPOSIT_AMOUNT_IND = 1;
uint256 constant MAIN_WITHDRAW_AMOUNT_IND = 2;
uint256 constant MAIN_ADDED_AMOUNT_ZKP_IND = 3;
uint256 constant MAIN_TOKEN_IND = 4;
uint256 constant MAIN_TOKEN_ID_IND = 5;
uint256 constant MAIN_SPEND_TIME_IND = 6;
uint256 constant MAIN_ZASSET_UTXO_IN_NULLIFIER_1_IND = 7;
uint256 constant MAIN_ZASSET_UTXO_IN_NULLIFIER_2_IND = 8;
uint256 constant MAIN_ZACCOUNT_UTXO_IN_NULLIFIER_IND = 9;
uint256 constant MAIN_ZZONE_DATA_ESCROW_EPHIMERAL_PUB_KEY_AX_IND = 10;
uint256 constant MAIN_ZZONE_DATA_ESCROW_ENCRYPTED_MESSAGE_AX_IND = 11;
uint256 constant MAIN_KYT_DEPOSIT_SIGNED_MESSAGE_SENDER_IND = 12;
uint256 constant MAIN_KYT_DEPOSIT_SIGNED_MESSAGE_RECEIVER_IND = 13;
uint256 constant MAIN_KYT_DEPOSIT_SIGNED_MESSAGE_HASH_IND = 14;
uint256 constant MAIN_KYT_WITHDRAW_SIGNED_MESSAGE_SENDER_IND = 15;
uint256 constant MAIN_KYT_WITHDRAW_SIGNED_MESSAGE_RECEIVER_IND = 16;
uint256 constant MAIN_KYT_WITHDRAW_SIGNED_MESSAGE_HASH_IND = 17;
uint256 constant MAIN_DATA_ESCROW_EPHIMERAL_PUB_KEY_AX_IND = 18;
// indexes 19 to 28 are MAIN_DATA_ESCROW_ENCRYPTED_MESSAGE_AX_IND
uint256 constant MAIN_DAO_DATA_ESCROW_EPHIMERAL_PUB_KEY_AX_IND = 29;
// indexes 30 to 32 are MAIN_DAO_DATA_ESCROW_ENCRYPTED_MESSAGE_AX_IND
uint256 constant MAIN_UTXO_OUT_CREATE_TIME_IND = 33;
uint256 constant MAIN_ZASSET_UTXO_OUT_COMMITMENT_1_IND = 34;
uint256 constant MAIN_ZASSET_UTXO_OUT_COMMITMENT_2_IND = 35;
uint256 constant MAIN_ZACCOUNT_UTXO_OUT_COMMITMENT_IND = 36;
uint256 constant MAIN_CHARGED_AMOUNT_ZKP_IND = 37;
uint256 constant MAIN_ZNETWORK_CHAIN_ID_IND = 38;
uint256 constant MAIN_STATIC_MERKLE_ROOT_IND = 39;
uint256 constant MAIN_FOREST_MERKLE_ROOT_IND = 40;
uint256 constant MAIN_SALT_HASH_IND = 41;
uint256 constant MAIN_MAGICAL_CONSTRAINT_IND = 42;
