// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: Copyright 2024 Panther Ventures Limited Gibraltar
pragma solidity ^0.8.19;

uint256 constant PRP_CLAIM_EXTRA_INPUT_HASH = 0;
uint256 constant PRP_CLAIM_ADDED_AMOUNT_ZKP = 1;
uint256 constant PRP_CLAIM_CHARGED_AMOUNT_ZKP = 2;
uint256 constant PRP_CLAIM_UTXO_OUT_CREATE_TIME = 3;
uint256 constant PRP_CLAIM_DEPOSIT_PRP_AMOUNT = 4;
uint256 constant PRP_CLAIM_WITHDRAW_PRP_AMOUNT = 5;
uint256 constant PRP_CLAIM_UTXO_COMMITMENT_PRIVATE_PART = 6;
uint256 constant PRP_CLAIM_UTXO_SPEND_PUB_KEY_X = 7;
uint256 constant PRP_CLAIM_UTXO_SPEND_PUB_KEY_Y = 8;
uint256 constant PRP_CLAIM_ZASSET_SCALE = 9;
uint256 constant PRP_CLAIM_ZACCOUNT_UTXO_IN_NULLIFIER = 10;
uint256 constant PRP_CLAIM_ZACCOUNT_UTXO_OUT_COMMITMENT = 11;
uint256 constant PRP_CLAIM_ZNETWORK_CHAIN_ID = 12;
uint256 constant PRP_CLAIM_STATIC_MERKLE_ROOT = 13;
uint256 constant PRP_CLAIM_FOREST_MERKLE_ROOT = 14;
uint256 constant PRP_CLAIM_SALT_HASH = 15;
uint256 constant PRP_CLAIM_MAGICAL_CONSTRAINT = 16;
