// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: Copyright 2024 Panther Ventures Limited Gibraltar
pragma solidity ^0.8.19;

// Indexes of public input for the prpAccountConversion zk-circuit follows

uint256 constant PRP_CONVERSION_EXTRA_INPUT_HASH_IND = 0;
uint256 constant PRP_CONVERSION_ADDED_AMOUNT_ZKP_IND = 1;
uint256 constant PRP_CONVERSION_CHARGED_AMOUNT_ZKP_IND = 2;
uint256 constant PRP_CONVERSION_UTXO_OUT_CREATE_TIME_IND = 3;
uint256 constant PRP_CONVERSION_DEPOSIT_PRP_AMOUNT_IND = 4;
uint256 constant PRP_CONVERSION_WITHDRAW_PRP_AMOUNT_IND = 5;
uint256 constant PRP_CONVERSION_UTXO_COMMITMENT_PRIVATE_PART_IND = 6;
uint256 constant PRP_CONVERSION_UTXO_SPEND_PUB_KEY_X_IND = 7;
uint256 constant PRP_CONVERSION_UTXO_SPEND_PUB_KEY_Y_IND = 8;
uint256 constant PRP_CONVERSION_ZASSET_SCALE_IND = 9;
uint256 constant PRP_CONVERSION_ZACCOUNT_UTXO_IN_NULLIFIER_IND = 10;
uint256 constant PRP_CONVERSION_ZACCOUNT_UTXO_OUT_COMMITMENT_IND = 11;
uint256 constant PRP_CONVERSION_ZNETWORK_CHAIN_ID_IND = 12;
uint256 constant PRP_CONVERSION_STATIC_MERKLE_ROOT_IND = 13;
uint256 constant PRP_CONVERSION_FOREST_MERKLE_ROOT_IND = 14;
uint256 constant PRP_CONVERSION_SALT_HASH_IND = 15;
uint256 constant PRP_CONVERSION_MAGICAL_CONSTRAINT_IND = 16;
