// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: Copyright 2024 Panther Ventures Limited Gibraltar
pragma solidity ^0.8.19;

// Indexes of public input for the zAccountActivation zk-circuit follows

uint256 constant ZACCOUNT_ACTIVATION_EXTRA_INPUT_HASH_IND = 0;
uint256 constant ZACCOUNT_ACTIVATION_ADDED_AMOUNT_ZKP_IND = 1;
uint256 constant ZACCOUNT_ACTIVATION_CHARGED_AMOUNT_ZKP_IND = 2;
uint256 constant ZACCOUNT_ACTIVATION_ZACCOUNT_ID_IND = 3;
uint256 constant ZACCOUNT_ACTIVATION_UTXO_OUT_CREATE_TIME_IND = 4;
uint256 constant ZACCOUNT_ACTIVATION_ROOT_SPEND_PUB_KEY_X_IND = 5;
uint256 constant ZACCOUNT_ACTIVATION_ROOT_SPEND_PUB_KEY_Y_IND = 6;
uint256 constant ZACCOUNT_ACTIVATION_ROOT_READ_PUB_KEY_X_IND = 7;
uint256 constant ZACCOUNT_ACTIVATION_ROOT_READ_PUB_KEY_Y_IND = 8;
uint256 constant ZACCOUNT_ACTIVATION_ZACCOUNT_NULLIFIER_PUB_KEY_X_IND = 9;
uint256 constant ZACCOUNT_ACTIVATION_ZACCOUNT_NULLIFIER_PUB_KEY_Y_IND = 10;
uint256 constant ZACCOUNT_ACTIVATION_MASTER_EOA_IND = 11;
uint256 constant ZACCOUNT_ACTIVATION_NULLIFIER_ZONE_IND = 12;
uint256 constant ZACCOUNT_ACTIVATION_UTXO_OUT_COMMITMENT_IND = 13;
uint256 constant ZACCOUNT_ACTIVATION_KYC_SIGNED_MESSAGE_HASH_IND = 14;
uint256 constant ZACCOUNT_ACTIVATION_STATIC_MERKLE_ROOT_IND = 15;
uint256 constant ZACCOUNT_ACTIVATION_FOREST_MERKLE_ROOT_IND = 16;
uint256 constant ZACCOUNT_ACTIVATION_SALT_HASH_IND = 17;
uint256 constant ZACCOUNT_ACTIVATION_MAGICAL_CONSTRAINT_IND = 18;
