// SPDX-License-Identifier: BUSL-1.1
// SPDX-FileCopyrightText: Copyright 2024 Panther Ventures Limited Gibraltar
pragma solidity ^0.8.19;

uint256 constant ZACCOUNT_ACTIVATION_EXTRA_INPUT_HASH = 0;
uint256 constant ZACCOUNT_ACTIVATION_ADDED_AMOUNT_ZKP = 1;
uint256 constant ZACCOUNT_ACTIVATION_CHARGED_AMOUNT_ZKP = 2;
uint256 constant ZACCOUNT_ACTIVATION_ZACCOUNT_ID = 3;
uint256 constant ZACCOUNT_ACTIVATION_UTXO_OUT_CREATE_TIME = 4;
uint256 constant ZACCOUNT_ACTIVATION_ROOT_SPEND_PUB_KEY_X = 5;
uint256 constant ZACCOUNT_ACTIVATION_ROOT_SPEND_PUB_KEY_Y = 6;
uint256 constant ZACCOUNT_ACTIVATION_ROOT_READ_PUB_KEY_X = 7;
uint256 constant ZACCOUNT_ACTIVATION_ROOT_READ_PUB_KEY_Y = 8;
uint256 constant ZACCOUNT_ACTIVATION_ZACCOUNT_NULLIFIER_PUB_KEY_X = 9;
uint256 constant ZACCOUNT_ACTIVATION_ZACCOUNT_NULLIFIER_PUB_KEY_Y = 10;
uint256 constant ZACCOUNT_ACTIVATION_MASTER_EOA = 11;
uint256 constant ZACCOUNT_ACTIVATION_NULLIFIER_ZONE = 12;
uint256 constant ZACCOUNT_ACTIVATION_UTXO_OUT_COMMITMENT = 13;
uint256 constant ZACCOUNT_ACTIVATION_KYC_SIGNED_MESSAGE_HASH = 14;
uint256 constant ZACCOUNT_ACTIVATION_STATIC_MERKLE_ROOT = 15;
uint256 constant ZACCOUNT_ACTIVATION_FOREST_MERKLE_ROOT = 16;
uint256 constant ZACCOUNT_ACTIVATION_SALT_HASH = 17;
uint256 constant ZACCOUNT_ACTIVATION_MAGICAL_CONSTRAINT = 18;
