// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: Copyright 2024 Panther Ventures Limited Gibraltar
pragma solidity ^0.8.19;

import { ZERO_VALUE, EIGHT_LEVELS } from "./Constants.sol";

// @notice The binary Merkle tree of eight levels populated with zero leaf values
abstract contract EightLevelZeroTree {
    // @param level From 0 for the leaf up to EIGHT_LEVELS for the root
    function getZeroNodeAtLevel(uint256 level) internal pure returns (bytes32) {
        require(level < EIGHT_LEVELS + 1, "EZT:E1");

        // Generated by `../../../../lib/binaryMerkleZerosContractGenerator.ts`
        uint256 zeroNode = [
            // Leaf with the zero value
            uint256(ZERO_VALUE),
            // Roots of branches containing zero leafs only, one root per level
            0x232fc5fea3994c77e07e1bab1ec362727b0f71f291c17c34891dd4faf1457bd4,
            0x077851cf613fd96280795a3cabc89663f524b1b545a3b1c7c79130b0f7d251c8,
            0x1d79fd0bc46f7ca934dbcd3386a06f03c43f497851b3815ee726e7f9b26e504c,
            0x05c0c15753806f506f64c18bf07116542451822479c4a89305cd4eb7ee94c800,
            0x2b56fd5e780ebebdacdd27e6464cf01aac089461a998814974a7504aabb2023f,
            0x2e99dc37b0a4f107b20278c26562b55df197e0b3eb237ec672f4cf729d159b69,
            0x225624653ac89fe211c0c3d303142a4caf24eb09050be08c33af2e7a1e372a0f,
            // Root of the tree fully populated with zero leafs only
            0x276c76358db8af465e2073e4b25d6b1d83f0b9b077f8bd694deefe917e2028d7
        ][level];

        return bytes32(zeroNode);
    }
}
